#!/bin/bash
# ==============================================================================
# GMS Database Least Privilege Role Initialization (TASK 6 / P1 HIGH)
# ==============================================================================
# Separates administrative PostgreSQL superuser from application runtime.
# Roles:
# 1. gms_owner       : Schema & Migration DDL Owner
# 2. gms_app         : Application Runtime (SELECT, INSERT, UPDATE, DELETE)
# 3. gms_backup      : Backup Operator (pg_dump read access)
# 4. restore_operator: Isolated Restore Operator
# ==============================================================================

set -Eeuo pipefail

APP_USER="${GMS_APP_USER:-gms_app}"
APP_PASSWORD="${GMS_APP_PASSWORD:-$POSTGRES_PASSWORD}"
OWNER_USER="${GMS_OWNER_USER:-gms_owner}"
OWNER_PASSWORD="${GMS_OWNER_PASSWORD:-$POSTGRES_PASSWORD}"
BACKUP_USER="${GMS_BACKUP_USER:-gms_backup}"
BACKUP_PASSWORD="${GMS_BACKUP_PASSWORD:-$POSTGRES_PASSWORD}"
RESTORE_USER="${GMS_RESTORE_USER:-restore_operator}"
RESTORE_PASSWORD="${GMS_RESTORE_PASSWORD:-$POSTGRES_PASSWORD}"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  DO \$\$
  BEGIN
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '$OWNER_USER') THEN
      CREATE ROLE $OWNER_USER WITH LOGIN PASSWORD '$OWNER_PASSWORD' CREATEDB;
    ELSE
      ALTER ROLE $OWNER_USER WITH PASSWORD '$OWNER_PASSWORD';
    END IF;

    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '$APP_USER') THEN
      CREATE ROLE $APP_USER WITH LOGIN PASSWORD '$APP_PASSWORD' NOSUPERUSER NOCREATEDB NOCREATEROLE;
    ELSE
      ALTER ROLE $APP_USER WITH PASSWORD '$APP_PASSWORD';
    END IF;

    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '$BACKUP_USER') THEN
      CREATE ROLE $BACKUP_USER WITH LOGIN PASSWORD '$BACKUP_PASSWORD' NOSUPERUSER NOCREATEDB NOCREATEROLE;
    ELSE
      ALTER ROLE $BACKUP_USER WITH PASSWORD '$BACKUP_PASSWORD';
    END IF;

    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '$RESTORE_USER') THEN
      CREATE ROLE $RESTORE_USER WITH LOGIN PASSWORD '$RESTORE_PASSWORD' CREATEDB;
    ELSE
      ALTER ROLE $RESTORE_USER WITH PASSWORD '$RESTORE_PASSWORD';
    END IF;
  END \$\$;

  GRANT ALL ON SCHEMA public TO $OWNER_USER;
  GRANT USAGE, CREATE ON SCHEMA public TO $APP_USER;
  GRANT USAGE ON SCHEMA public TO $BACKUP_USER;
  GRANT ALL ON SCHEMA public TO $RESTORE_USER;

  GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO $APP_USER;
  GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO $APP_USER;

  GRANT SELECT ON ALL TABLES IN SCHEMA public TO $BACKUP_USER;
  GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO $BACKUP_USER;

  ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO $APP_USER;
  ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO $APP_USER;
  ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO $BACKUP_USER;
  ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON SEQUENCES TO $BACKUP_USER;
EOSQL
