#!/bin/bash
# ==============================================================================
# GMS Database Least Privilege Role Initialization (P0 HIGH - ASVS L2 / SSDF)
# ==============================================================================
# Separates administrative PostgreSQL superuser from application runtime.
# Roles:
# 1. gms_owner       : Schema & Migration DDL Owner (NOSUPERUSER, NOCREATEDB)
# 2. gms_app         : Application Runtime (SELECT, INSERT, UPDATE, DELETE)
# 3. gms_backup      : Backup Operator (pg_dump read-only access)
# 4. restore_operator: Isolated Restore Operator
# ==============================================================================

set -Eeuo pipefail

APP_USER="${GMS_APP_USER:-gms_app}"
APP_PASSWORD="${GMS_APP_PASSWORD:?GMS_APP_PASSWORD is required and cannot be empty}"
OWNER_USER="${GMS_OWNER_USER:-gms_owner}"
OWNER_PASSWORD="${GMS_OWNER_PASSWORD:?GMS_OWNER_PASSWORD is required and cannot be empty}"
BACKUP_USER="${GMS_BACKUP_USER:-gms_backup}"
BACKUP_PASSWORD="${GMS_BACKUP_PASSWORD:?GMS_BACKUP_PASSWORD is required and cannot be empty}"
RESTORE_USER="${GMS_RESTORE_USER:-restore_operator}"
RESTORE_PASSWORD="${GMS_RESTORE_PASSWORD:?GMS_RESTORE_PASSWORD is required and cannot be empty}"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  DO \$\$
  BEGIN
    -- 1. Create or normalize gms_owner
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '$OWNER_USER') THEN
      EXECUTE format('CREATE ROLE %I WITH LOGIN PASSWORD %L NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS', '$OWNER_USER', '$OWNER_PASSWORD');
    ELSE
      EXECUTE format('ALTER ROLE %I WITH PASSWORD %L NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS', '$OWNER_USER', '$OWNER_PASSWORD');
    END IF;

    -- 2. Create or normalize gms_app
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '$APP_USER') THEN
      EXECUTE format('CREATE ROLE %I WITH LOGIN PASSWORD %L NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS', '$APP_USER', '$APP_PASSWORD');
    ELSE
      EXECUTE format('ALTER ROLE %I WITH PASSWORD %L NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS', '$APP_USER', '$APP_PASSWORD');
    END IF;

    -- 3. Create or normalize gms_backup
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '$BACKUP_USER') THEN
      EXECUTE format('CREATE ROLE %I WITH LOGIN PASSWORD %L NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS', '$BACKUP_USER', '$BACKUP_PASSWORD');
    ELSE
      EXECUTE format('ALTER ROLE %I WITH PASSWORD %L NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS', '$BACKUP_USER', '$BACKUP_PASSWORD');
    END IF;

    -- 4. Create or normalize restore_operator
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '$RESTORE_USER') THEN
      EXECUTE format('CREATE ROLE %I WITH LOGIN PASSWORD %L NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS', '$RESTORE_USER', '$RESTORE_PASSWORD');
    ELSE
      EXECUTE format('ALTER ROLE %I WITH PASSWORD %L NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS', '$RESTORE_USER', '$RESTORE_PASSWORD');
    END IF;
  END \$\$;

  -- 5. Revoke schema creation from PUBLIC, app, and backup
  REVOKE ALL ON SCHEMA public FROM PUBLIC;
  REVOKE CREATE ON SCHEMA public FROM PUBLIC, $APP_USER, $BACKUP_USER;
  GRANT USAGE, CREATE ON SCHEMA public TO $OWNER_USER;
  GRANT USAGE ON SCHEMA public TO $APP_USER, $BACKUP_USER;
  GRANT ALL ON SCHEMA public TO $RESTORE_USER;

  -- 6. Initial object privileges
  GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO $APP_USER;
  GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO $APP_USER;

  GRANT SELECT ON ALL TABLES IN SCHEMA public TO $BACKUP_USER;
  GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO $BACKUP_USER;

  -- 7. Set default privileges explicitly FOR ROLE gms_owner
  ALTER DEFAULT PRIVILEGES FOR ROLE $OWNER_USER IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO $APP_USER;
  ALTER DEFAULT PRIVILEGES FOR ROLE $OWNER_USER IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO $APP_USER;
  ALTER DEFAULT PRIVILEGES FOR ROLE $OWNER_USER IN SCHEMA public GRANT SELECT ON TABLES TO $BACKUP_USER;
  ALTER DEFAULT PRIVILEGES FOR ROLE $OWNER_USER IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO $BACKUP_USER;
EOSQL
