export const STATUS = {
  REGISTERED: 'REGISTERED',
  WEIGH_IN_DONE: 'WEIGH_IN_DONE',
  QC_VEHICLE_PENDING: 'QC_VEHICLE_PENDING',
  QC_VEHICLE_IN_PROGRESS: 'QC_VEHICLE_IN_PROGRESS',
  QC_VEHICLE_PASSED: 'QC_VEHICLE_PASSED',
  QC_VEHICLE_REJECTED: 'QC_VEHICLE_REJECTED',
  WAREHOUSE_IN_PROGRESS: 'WAREHOUSE_IN_PROGRESS',
  WAREHOUSE_DONE: 'WAREHOUSE_DONE',
  INCOMING_CHECK_PENDING: 'INCOMING_CHECK_PENDING',
  INCOMING_CHECK_IN_PROGRESS: 'INCOMING_CHECK_IN_PROGRESS',
  INCOMING_CHECK_PASSED: 'INCOMING_CHECK_PASSED',
  INCOMING_CHECK_REJECTED: 'INCOMING_CHECK_REJECTED',
  WEIGH_OUT_DONE: 'WEIGH_OUT_DONE',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED'
};
