import { IsNotEmpty, IsString, IsOptional } from 'class-validator';
import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';

export class CreateSystemIssueDto {
  @ApiProperty({
    description: 'Type of the issue reported',
    example: 'Login Issue',
  })
  @IsNotEmpty()
  @IsString()
  issueType: string;

  @ApiProperty({
    description: 'Detailed description of the issue',
    example: 'Cannot log in with the temporary password generated by admin.',
  })
  @IsNotEmpty()
  @IsString()
  description: string;

  @ApiPropertyOptional({
    description: 'Optional Base64 or URL screenshot of the issue',
    example: 'data:image/png;base64,iVBORw0KGgo...',
  })
  @IsOptional()
  @IsString()
  screenshotUrl?: string;
}
